export const FRONTEND_JS = [
  '(function(){"use strict";',

  // ── CONFIG ────────────────────────────────────────────────────────────────
  'var CONFIG=Object.freeze({',
  '  courts:[',
  '    "IN THE COURT OF SH. DHARMINDER PAUL SINGLA, SESSIONS JUDGE, FAZILKA",',
  '    "IN THE COURT OF SH. KRISHAN KUMAR SINGLA, ASJ, FAZILKA",',
  '    "IN THE COURT OF MRS. PAMELPREET GREWAL KAHAL, ASJ, FAZILKA",',
  '    "IN THE COURT OF MRS. PAMELPREET GREWAL KAHAL, JUDGE, SPECIAL COURT, FAZILKA",',
  '    "IN THE COURT OF SH. AJIT PAL SINGH, ASJ, FAZILKA",',
  '    "IN THE COURT OF SH. ATUL KAMBOJ, ASJ, FAZILKA",',
  '    "IN THE COURT OF SH. HARPREET SINGH, JMIC, FAZILKA",',
  '    "IN THE COURT OF MS. KARAMWINDER KAUR, JMIC, FAZILKA"',
  '  ],',
  '  counsels:[',
  '    "Baltej Singh Brar, Advocate|Chief, LADC, Fazilka.",',
  '    "Hardeep Singh Dhaliwal, Advocate|Deputy Chief, LADC, Fazilka.",',
  '    "Sunil Rangbulla, Advocate|Deputy Chief, LADC, Fazilka.",',
  '    "Rajvinder Kaur, Advocate|Assistant, LADC, Fazilka.",',
  '    "Amisha, Advocate|Assistant, LADC, Fazilka.",',
  '    "Naazpreet Kaur, Advocate|Assistant, LADC, Fazilka."',
  '  ],',
  '  proformas:[',
  '    {id:"original",   name:"Standard Exemption",  reason:"illness",                        stage:"the purpose fixed"},',
  '    {id:"medical",    name:"Medical Emergency",   reason:"a sudden medical emergency",     stage:"the purpose fixed"},',
  '    {id:"hospital",   name:"Hospitalization",     reason:"hospitalization",                stage:"the purpose fixed"},',
  '    {id:"bereavement",name:"Bereavement",         reason:"a bereavement in the family",    stage:"the purpose fixed"},',
  '    {id:"elderly",    name:"Senior Citizen",      reason:"age-related health constraints", stage:"the purpose fixed"}',
  '  ]',
  '});',

  // ── STATE ─────────────────────────────────────────────────────────────────
  'var state={zoom:0.5,people:[{name:"",role:"Accused/applicant"}],clauses:[],exporting:false};',

  // ── UTILITIES ─────────────────────────────────────────────────────────────
  'function $(id){return document.getElementById(id);}',
  'function fv(id){var e=$(id);return e?e.value.trim():"";}',
  'function clean(s){return String(s||"").replace(/\\s+/g," ").trim();}',
  'function esc(s){return String(s||"").replace(/[&<>"\']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",\'"\':\'&quot;\',"\'":"&#39;"}[c];});}',
  'function escAttr(s){return String(s||"").replace(/"/g,"&quot;");}',
  'var _rt;function debounce(fn,ms){return function(){clearTimeout(_rt);_rt=setTimeout(function(){fn();},ms);};}',

  // ── TEXT GENERATION ───────────────────────────────────────────────────────
  'function getNames(){',
  '  var a=state.people.map(function(p){return clean(p.name);}).filter(Boolean);',
  '  if(!a.length)return "";',
  '  if(a.length===1)return a[0];',
  '  if(a.length===2)return a[0]+" and "+a[1];',
  '  return a.slice(0,-1).join(", ")+" and "+a[a.length-1];',
  '}',
  'function isPlural(){return state.people.filter(function(p){return clean(p.name);}).length>1;}',
  'function applicantText(){return getNames()||fv("rightParty")||"Accused/applicant";}',
  'function accusedLabel(){return isPlural()?"Accused/applicants":"Accused/applicant";}',

  'function generateSubject(){',
  '  var n=getNames();',
  '  return "Subject: Application for exemption of personal appearance"+(n?" of "+n:"")+".";',
  '}',

  'function generatePrayer(){',
  '  return "It is, therefore, most respectfully prayed that in light of the facts and circumstances stated above, the personal appearance of the "+',
  '    (isPlural()?"above-named accused/applicants":"above-named accused/applicant")+',
  '    " may kindly be exempted for today only. Any other order(s) that this Hon\'ble Court deems fit and proper may also be passed.";',
  '}',

  'function generateDefaultClauses(){',
  '  var stage=fv("caseStage")||"the purpose fixed";',
  '  var n=getNames();',
  '  var r=fv("reason")||"illness";',
  '  var subj=n?(isPlural()?"That the accused/applicants, namely "+n+", are":"That the accused/applicant, "+n+", is"):"That the accused/applicant is";',
  '  return [',
  '    "That the above-noted case is pending before this Hon\'ble Court and the same is fixed for today for "+stage+".",',
  '    subj+" unable to appear before this Hon\'ble Court today due to "+r+".",',
  '    "That the absence of the accused/applicant is neither willful nor intentional, but is solely on account of the aforesaid reason.",',
  '    "That no prejudice shall be caused to the opposite party by the grant of this exemption."',
  '  ];',
  '}',

  // ── CSS ───────────────────────────────────────────────────────────────────
  'function getCSS(){return [',
  '  ":root{--z:0.5;--col-bg:#f0f2f5;--col-surface:#ffffff;--col-surface-2:#f8f9fc;--col-border:#d8dce6;--col-border-2:#eaecf2;--col-text:#111827;--col-text-2:#4b5563;--col-text-3:#9ca3af;--col-accent:#3b6fce;--col-accent-h:#2f5db5;--col-accent-s:rgba(59,111,206,.12);--col-danger:#dc2626;--col-danger-s:rgba(220,38,38,.08);--col-success:#16a34a;--col-warn:#d97706;--shadow-sm:0 1px 3px rgba(0,0,0,.06),0 1px 2px rgba(0,0,0,.04);--shadow-md:0 4px 12px rgba(0,0,0,.08),0 2px 4px rgba(0,0,0,.04);--shadow-lg:0 10px 30px rgba(0,0,0,.12),0 4px 8px rgba(0,0,0,.06);--shadow-paper:0 4px 24px rgba(0,0,0,.18),0 1px 4px rgba(0,0,0,.1);--r-sm:4px;--r-md:8px;--r-lg:12px;--font-sans:\'Inter\',-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif;--font-serif:\'Times New Roman\',Times,Georgia,serif;--tr-fast:120ms ease;--tr-base:200ms ease;}",',
  '  "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0;}",',
  '  "html{font-size:14px;-webkit-text-size-adjust:100%;}",',
  '  "body{font-family:var(--font-sans);background:var(--col-bg);color:var(--col-text);height:100dvh;display:flex;flex-direction:column;overflow:hidden;line-height:1.5;}",',
  '  "::-webkit-scrollbar{width:6px;height:6px;}",',
  '  "::-webkit-scrollbar-track{background:transparent;}",',
  '  "::-webkit-scrollbar-thumb{background:var(--col-border);border-radius:3px;}",',
  '  "::-webkit-scrollbar-thumb:hover{background:var(--col-text-3);}",',
  '  ".app-header{background:var(--col-surface);border-bottom:1px solid var(--col-border);padding:0 20px;height:52px;display:flex;align-items:center;justify-content:space-between;flex-shrink:0;box-shadow:var(--shadow-sm);z-index:30;}",',
  '  ".header-brand{display:flex;align-items:center;gap:10px;}",',
  '  ".header-icon{width:30px;height:30px;background:linear-gradient(135deg,var(--col-accent),#6c8fd8);border-radius:var(--r-sm);display:flex;align-items:center;justify-content:center;flex-shrink:0;}",',
  '  ".header-icon svg{width:16px;height:16px;}",',
  '  ".app-title{font-size:15px;font-weight:700;letter-spacing:-.3px;color:var(--col-text);}",',
  '  ".app-title span{font-weight:400;color:var(--col-text-2);margin-left:2px;}",',
  '  ".header-badge{font-size:10px;font-weight:600;background:var(--col-accent-s);color:var(--col-accent);border-radius:20px;padding:2px 8px;letter-spacing:.3px;text-transform:uppercase;}",',
  '  ".mobile-tabs{display:flex;gap:2px;background:var(--col-bg);border-radius:var(--r-md);padding:3px;}",',
  '  ".mobile-tabs button{background:transparent;border:none;padding:5px 14px;border-radius:6px;font-size:12px;font-weight:600;color:var(--col-text-2);cursor:pointer;transition:background var(--tr-fast),color var(--tr-fast);}",',
  '  ".mobile-tabs button.active{background:var(--col-surface);color:var(--col-text);box-shadow:var(--shadow-sm);}",',
  '  ".layout{display:flex;flex:1;overflow:hidden;min-height:0;}",',
  '  ".panel{overflow-y:auto;height:100%;-webkit-overflow-scrolling:touch;}",',
  '  ".form-panel{background:var(--col-surface);padding:20px 24px 100px;flex:1;border-right:1px solid var(--col-border);}",',
  '  ".preview-panel{background:#c9cdd8;background-image:linear-gradient(rgba(255,255,255,.03) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.03) 1px,transparent 1px);background-size:20px 20px;flex:1;position:relative;}",',
  '  ".section-title{font-size:10.5px;font-weight:700;text-transform:uppercase;letter-spacing:.7px;color:var(--col-text-3);border-bottom:1px solid var(--col-border-2);padding-bottom:8px;margin:28px 0 14px;display:flex;justify-content:space-between;align-items:center;}",',
  '  ".section-title:first-child{margin-top:2px;}",',
  '  ".grid{display:grid;gap:12px;}",',
  '  ".grid.two{grid-template-columns:1fr;}",',
  '  ".stack{display:flex;flex-direction:column;gap:8px;}",',
  '  "label:not(.checkbox-label){display:block;font-size:11.5px;font-weight:600;color:var(--col-text-2);margin:10px 0 4px;letter-spacing:.1px;}",',
  '  ".field{width:100%;background:var(--col-surface);border:1.5px solid var(--col-border);border-radius:var(--r-sm);padding:8px 11px;font-size:13px;font-family:var(--font-sans);color:var(--col-text);outline:none;transition:border-color var(--tr-fast),box-shadow var(--tr-fast),background var(--tr-fast);line-height:1.45;}",',
  '  ".field:hover{border-color:#b0b8cc;}",',
  '  ".field:focus{border-color:var(--col-accent);box-shadow:0 0 0 3px var(--col-accent-s);background:#fff;}",',
  '  ".field::placeholder{color:var(--col-text-3);}",',
  '  ".field:disabled{background:var(--col-surface-2);color:var(--col-text-3);cursor:not-allowed;}",',
  '  ".field.error{border-color:var(--col-danger);box-shadow:0 0 0 3px var(--col-danger-s);}",',
  '  "select.field{appearance:none;background-image:url(\\"data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'12\' height=\'12\' viewBox=\'0 0 24 24\' fill=\'none\' stroke=\'%236b7280\' stroke-width=\'2.5\' stroke-linecap=\'round\' stroke-linejoin=\'round\'%3E%3Cpolyline points=\'6 9 12 15 18 9\'/%3E%3C/svg%3E\\");background-repeat:no-repeat;background-position:right 10px center;background-size:12px;padding-right:30px;cursor:pointer;}",',
  '  "textarea.field{resize:vertical;min-height:52px;line-height:1.5;}",',
  '  ".btn{border:none;border-radius:var(--r-sm);font-size:13px;font-weight:600;font-family:var(--font-sans);cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:6px;min-height:36px;padding:0 16px;transition:background var(--tr-fast),color var(--tr-fast),box-shadow var(--tr-fast),transform var(--tr-fast);white-space:nowrap;user-select:none;-webkit-tap-highlight-color:transparent;}",',
  '  ".btn:active{transform:translateY(1px);}",',
  '  ".btn.primary{background:var(--col-accent);color:#fff;box-shadow:0 1px 3px rgba(59,111,206,.4);}",',
  '  ".btn.primary:hover{background:var(--col-accent-h);box-shadow:0 2px 6px rgba(59,111,206,.5);}",',
  '  ".btn.primary:active{background:#264e9f;}",',
  '  ".btn.primary:disabled{background:#93aed8;box-shadow:none;cursor:not-allowed;transform:none;}",',
  '  ".btn.secondary{background:var(--col-surface-2);color:var(--col-text);border:1.5px solid var(--col-border);}",',
  '  ".btn.secondary:hover{background:#eef0f6;border-color:#b8bfd4;}",',
  '  ".btn.secondary:active{background:#e4e8f0;}",',
  '  ".btn.outline-btn{background:transparent;border:1.5px dashed var(--col-border);color:var(--col-text-2);font-size:12px;}",',
  '  ".btn.outline-btn:hover{background:var(--col-surface-2);border-color:#a0aabf;color:var(--col-text);}",',
  '  ".btn.text-btn{background:transparent;color:var(--col-accent);min-height:unset;padding:2px 4px;font-size:12px;border-radius:var(--r-sm);}",',
  '  ".btn.text-btn:hover{background:var(--col-accent-s);}",',
  '  ".btn.ghost{background:transparent;color:var(--col-text-3);width:32px;min-height:32px;padding:0;border:1.5px solid transparent;border-radius:var(--r-sm);font-size:13px;}",',
  '  ".btn.ghost:hover{background:var(--col-danger-s);color:var(--col-danger);border-color:rgba(220,38,38,.2);}",',
  '  ".applicant-row,.clause-row{display:flex;gap:8px;align-items:flex-start;padding:10px 12px;background:var(--col-surface-2);border:1.5px solid var(--col-border-2);border-radius:var(--r-md);transition:border-color var(--tr-base),box-shadow var(--tr-base);}",',
  '  ".applicant-row:hover,.clause-row:hover{border-color:var(--col-border);box-shadow:var(--shadow-sm);}",',
  '  ".clause-row .clause-num{font-size:12px;font-weight:700;color:var(--col-accent);padding-top:10px;width:22px;text-align:right;flex-shrink:0;}",',
  '  ".checkbox-label{display:flex;align-items:center;gap:8px;font-size:12.5px;font-weight:500;color:var(--col-text-2);cursor:pointer;margin:0;user-select:none;}",',
  '  ".checkbox-label input[type=checkbox]{width:15px;height:15px;accent-color:var(--col-accent);cursor:pointer;flex-shrink:0;}",',
  '  ".paper-stage{padding:28px;display:flex;justify-content:center;align-items:flex-start;transform-origin:top center;min-height:100%;}",',
  '  ".paper{background:white;width:612px;min-height:1008px;box-shadow:var(--shadow-paper);transform:scale(var(--z));transform-origin:top center;border-radius:2px;transition:box-shadow .2s;}",',
  '  ".paper-inner{padding:72px;font-family:var(--font-serif);color:#000;position:relative;min-height:1008px;}",',
  '  ".stamp-box{position:absolute;top:28px;right:38px;width:104px;height:122px;border:1.5px solid #555;display:flex;align-items:center;justify-content:center;text-align:center;font-family:var(--font-sans);font-size:9.5px;font-weight:700;color:#555;letter-spacing:.3px;text-transform:uppercase;background:repeating-linear-gradient(45deg,#fff,#fff 4px,#f5f5f5 4px,#f5f5f5 8px);border-radius:2px;}",',
  '  ".court{text-align:center;font-weight:bold;text-transform:uppercase;margin-bottom:20px;position:relative;z-index:2;font-size:inherit;line-height:1.4;}",',
  '  ".case-grid{margin-bottom:20px;font-weight:bold;position:relative;overflow:hidden;line-height:1.5;}",',
  '  ".case-left{width:45%;float:left;}",',
  '  ".case-right{width:45%;float:right;text-align:right;}",',
  '  ".case-vs{position:absolute;left:50%;transform:translateX(-50%);text-align:center;}",',
  '  ".case-grid::after{content:\'\';display:table;clear:both;}",',
  '  ".fir-info,.case-info{text-align:center;font-weight:normal;margin-top:10px;clear:both;}",',
  '  ".subject{font-weight:bold;text-decoration:underline;text-underline-offset:3px;margin:20px 0;text-align:justify;}",',
  '  ".salutation{margin-bottom:10px;}",',
  '  ".intro{margin-bottom:14px;margin-left:36px;}",',
  '  ".clause{display:flex;margin-bottom:10px;}",',
  '  ".clause .clause-num{width:28px;flex-shrink:0;font-weight:normal;}",',
  '  ".clause .clause-text{text-align:justify;flex:1;}",',
  '  ".prayer{margin:20px 0 36px 36px;text-align:justify;}",',
  '  ".sig-grid{display:flex;justify-content:space-between;margin-bottom:36px;}",',
  '  ".sig-right{text-align:right;}",',
  '  ".sig-name{display:inline-block;font-weight:bold;text-align:center;}",',
  '  ".counsel-label{text-align:center;margin-bottom:28px;}",',
  '  ".counsel-details{text-align:center;}",',
  '  ".action-bar{background:var(--col-surface);border-top:1px solid var(--col-border);padding:12px 20px;display:flex;justify-content:flex-end;align-items:center;gap:10px;z-index:20;flex-shrink:0;box-shadow:0 -2px 12px rgba(0,0,0,.05);}",',
  '  ".action-bar .btn{min-height:38px;padding:0 20px;}",',
  '  "@keyframes _spin{to{transform:rotate(360deg);}}",',
  '  ".btn-spinner{width:14px;height:14px;border:2px solid rgba(255,255,255,.4);border-top-color:#fff;border-radius:50%;animation:_spin .7s linear infinite;flex-shrink:0;}",',
  '  ".btn-spinner.dark{border-color:rgba(0,0,0,.15);border-top-color:var(--col-text-2);}",',
  '  ".toast-host{position:fixed;bottom:80px;right:20px;z-index:1000;display:flex;flex-direction:column;gap:8px;pointer-events:none;}",',
  '  ".toast{background:var(--col-text);color:#fff;font-size:13px;font-weight:500;padding:10px 16px;border-radius:var(--r-md);box-shadow:var(--shadow-md);display:flex;align-items:center;gap:8px;opacity:0;transform:translateY(8px);transition:opacity .25s,transform .25s;pointer-events:auto;max-width:320px;}",',
  '  ".toast.show{opacity:1;transform:none;}",',
  '  ".toast.success{background:#14532d;}",',
  '  ".toast.error{background:#7f1d1d;}",',
  '  ".toast-icon{flex-shrink:0;font-size:14px;}",',
  '  ".exporting .paper{transform:none!important;box-shadow:none!important;}",',
  '  ".hidden{display:none!important;}",',
  '  "@media(max-width:899px){.view-preview .form-panel{display:none;}.view-form .preview-panel{display:none;}.action-bar{justify-content:stretch;padding:10px 14px;}.action-bar .btn{flex:1;min-height:46px;}.form-panel{padding:16px 16px 120px;}}",',
  '  "@media(min-width:900px){.mobile-tabs{display:none;}.form-panel{max-width:460px;}.grid.two{grid-template-columns:1fr 1fr;}.preview-panel{display:flex;flex-direction:column;}.preview-panel .paper-stage{flex:1;overflow-y:auto;}}",',
  '  "@media(min-width:1280px){.form-panel{max-width:500px;}}"',
  '].join("");}',

  // ── HTML ──────────────────────────────────────────────────────────────────
  'function getHTML(){return [',
  '  \'<div class="app-header" role="banner">\',',
  '  \'  <div class="header-brand">\',',
  '  \'    <div class="header-icon" aria-hidden="true">\',',
  '  \'      <svg viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\',',
  '  \'        <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14 2 14 8 20 8"/>\',',
  '  \'        <line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><line x1="10" y1="9" x2="8" y2="9"/>\',',
  '  \'      </svg></div>\',',
  '  \'    <span class="app-title">PDFWriter <span>Legal</span></span>\',',
  '  \'    <span class="header-badge">LADC Fazilka</span>\',',
  '  \'  </div>\',',
  '  \'  <div class="mobile-tabs" role="tablist" aria-label="View panels">\',',
  '  \'    <button id="formTab" role="tab" aria-selected="true" class="active">Editor</button>\',',
  '  \'    <button id="previewTab" role="tab" aria-selected="false">Preview</button>\',',
  '  \'  </div>\',',
  '  \'</div>\',',
  '  \'<div class="layout">\',',
  '  \'  <div class="panel form-panel" id="formPanel" role="tabpanel">\',',
  '  \'    <div class="section-title">Document Setup</div>\',',
  '  \'    <div class="grid two">\',',
  '  \'      <div><label for="proforma">Template Proforma</label><select id="proforma" class="field"></select></div>\',',
  '  \'      <div><label for="layoutStyle">Line Spacing</label><select id="layoutStyle" class="field"><option value="standard">Standard Legal (13pt)</option><option value="compact">Compact (12pt)</option></select></div>\',',
  '  \'    </div>\',',
  '  \'    <label class="checkbox-label" style="margin-top:14px;"><input type="checkbox" id="stampSpace" checked> Show Court Fee Stamp indicator</label>\',',
  '  \'    <div class="section-title">Case Information</div>\',',
  '  \'    <label for="court">Court / Presiding Officer</label>\',',
  '  \'    <select id="court" class="field"></select>\',',
  '  \'    <div class="grid two" style="margin-top:4px;">\',',
  '  \'      <div><label for="leftParty">State / Complainant</label><input id="leftParty" class="field" placeholder="State" autocomplete="off"></div>\',',
  '  \'      <div><label for="rightParty">Accused / Respondent</label><input id="rightParty" class="field" placeholder="Accused Name" autocomplete="off"></div>\',',
  '  \'    </div>\',',
  '  \'    <label for="caseMode">Proceeding Type</label>\',',
  '  \'    <select id="caseMode" class="field"><option value="fir">FIR / State Case</option><option value="appeal">Complaint / Appeal</option></select>\',',
  '  \'    <div id="firFields" class="grid two" style="margin-top:4px;">\',',
  '  \'      <div><label for="firNumber">FIR No.</label><input id="firNumber" class="field" placeholder="e.g. 42" autocomplete="off"></div>\',',
  '  \'      <div><label for="firDate">FIR Date</label><input id="firDate" class="field" placeholder="DD.MM.YYYY" autocomplete="off"></div>\',',
  '  \'      <div><label for="sections">Sections</label><input id="sections" class="field" placeholder="e.g. 302, 34 IPC" autocomplete="off"></div>\',',
  '  \'      <div><label for="policeStation">Police Station</label><input id="policeStation" class="field" placeholder="PS Name" autocomplete="off"></div>\',',
  '  \'    </div>\',',
  '  \'    <div id="appealFields" class="grid two hidden" style="margin-top:4px;">\',',
  '  \'      <div><label for="caseType">Case Type</label><input id="caseType" class="field" placeholder="e.g. NACT" autocomplete="off"></div>\',',
  '  \'      <div><label for="caseNumber">Number / Year</label><input id="caseNumber" class="field" placeholder="e.g. 123/2024" autocomplete="off"></div>\',',
  '  \'    </div>\',',
  '  \'    <div class="section-title">Applicants <button id="addApplicant" class="btn text-btn">+ Add Person</button></div>\',',
  '  \'    <div id="applicantBox" class="stack"></div>\',',
  '  \'    <div class="section-title">Draft Body</div>\',',
  '  \'    <div class="grid two">\',',
  '  \'      <div><label for="reason">Reason for Absence</label><input id="reason" class="field" placeholder="illness" autocomplete="off"></div>\',',
  '  \'      <div><label for="caseStage">Stage of Case</label><input id="caseStage" class="field" placeholder="e.g. evidence" autocomplete="off"></div>\',',
  '  \'    </div>\',',
  '  \'    <label for="subject">Subject Line</label>\',',
  '  \'    <textarea id="subject" class="field" rows="2"></textarea>\',',
  '  \'    <div class="section-title">Clauses <button id="resetClauses" class="btn text-btn">Reset Default</button></div>\',',
  '  \'    <div id="clauseBox" class="stack"></div>\',',
  '  \'    <button id="addClause" class="btn outline-btn" style="width:100%;margin-top:8px;">+ Add Custom Clause</button>\',',
  '  \'    <label for="prayer" style="margin-top:18px;">Prayer</label>\',',
  '  \'    <textarea id="prayer" class="field" rows="4"></textarea>\',',
  '  \'    <div class="section-title">Signatures &amp; Execution</div>\',',
  '  \'    <div class="grid two">\',',
  '  \'      <div><label for="place">Place</label><input id="place" class="field" placeholder="Fazilka" value="Fazilka" autocomplete="off"></div>\',',
  '  \'      <div><label for="date">Date</label><input id="date" class="field" placeholder="DD.MM.YYYY" autocomplete="off"></div>\',',
  '  \'      <div><label for="salutation">Salutation</label><select id="salutation" class="field"><option>Respected Sir,</option><option>Respected Madam,</option></select></div>\',',
  '  \'      <div><label for="counsel">Filing Counsel</label><select id="counsel" class="field"></select></div>\',',
  '  \'    </div>\',',
  '  \'    <label class="checkbox-label" style="margin-top:14px;margin-bottom:32px;"><input id="duty" type="checkbox"> Append (Duty) to Counsel Title</label>\',',
  '  \'  </div>\',',
  '  \'  <div class="panel preview-panel" id="previewPanel" role="tabpanel">\',',
  '  \'    <div class="paper-stage" id="paperStage"><div id="paper" class="paper"></div></div>\',',
  '  \'  </div>\',',
  '  \'</div>\',',
  '  \'<div class="action-bar" role="toolbar">\',',
  '  \'  <button id="scanPdfBtn" class="btn secondary">Scanned PDF</button>\',',
  '  \'  <button id="realPdfBtn" class="btn primary">Export PDF</button>\',',
  '  \'</div>\',',
  '  \'<div class="toast-host" id="toastHost" aria-live="polite" aria-atomic="true"></div>\'',
  '].join("\\n");}',

  // ── TOAST ─────────────────────────────────────────────────────────────────
  'function showToast(msg,type,dur){',
  '  var host=$(\'toastHost\');if(!host)return;',
  '  var icons={success:"\\u2713",error:"\\u2715","default":"\\u2139"};',
  '  var t=document.createElement("div");',
  '  t.className="toast "+(type||"default");',
  '  t.innerHTML=\'<span class="toast-icon">\'+( icons[type]||icons["default"])+\'</span><span>\'+esc(msg)+"</span>";',
  '  host.appendChild(t);',
  '  requestAnimationFrame(function(){requestAnimationFrame(function(){t.classList.add("show");});});',
  '  setTimeout(function(){t.classList.remove("show");setTimeout(function(){t.remove();},300);},(dur||3500));',
  '}',

  // ── RENDER APPLICANTS ─────────────────────────────────────────────────────
  'function renderApplicants(){',
  '  $("applicantBox").innerHTML=state.people.map(function(p,i){',
  '    var del=state.people.length>1?\'<button class="btn ghost delApplicant" data-i="\'+i+\'" title="Remove">&#10005;</button>\':"";',
  '    return \'<div class="applicant-row">\'+',
  '      \'<div class="grid two" style="flex:1">\'+ ',
  '      \'<div><label>Applicant \'+(i+1)+\'</label><input class="field applicant" data-i="\'+i+\'" placeholder="Full Name" value="\'+escAttr(p.name)+\'" autocomplete="off"></div>\'+ ',
  '      \'<div><label>Role</label><div style="display:flex;gap:6px;align-items:flex-end"><input class="field role" data-i="\'+i+\'" value="\'+escAttr(p.role)+\'" autocomplete="off">\'+del+"</div></div>"+',
  '      "</div></div>";',
  '  }).join("");',
  '}',

  // ── RENDER CLAUSES ────────────────────────────────────────────────────────
  'function renderClauses(){',
  '  $("clauseBox").innerHTML=state.clauses.map(function(c,i){',
  '    return \'<div class="clause-row">\'+',
  '      \'<div class="clause-num">\'+(i+1)+\'.</div>\'+ ',
  '      \'<textarea class="field clauseText" data-i="\'+i+\'" rows="2">\'+esc(c)+"</textarea>"+',
  '      \'<button class="btn ghost delClause" data-i="\'+i+\'" title="Remove">&#10005;</button>\'+ ',
  '      "</div>";',
  '  }).join("");',
  '}',

  // ── RESET TEXT ────────────────────────────────────────────────────────────
  'function resetText(){',
  '  $("subject").value=generateSubject();',
  '  $("prayer").value=generatePrayer();',
  '  state.clauses=generateDefaultClauses();',
  '  renderClauses();updatePreview();',
  '}',

  'function applyProforma(){',
  '  var p=CONFIG.proformas.filter(function(x){return x.id===fv("proforma");})[0]||CONFIG.proformas[0];',
  '  $("reason").value=p.reason;',
  '  $("caseStage").value=p.stage;',
  '  resetText();',
  '}',

  // ── UPDATE PREVIEW ────────────────────────────────────────────────────────
  'function updatePreview(){',
  '  var cp=fv("counsel").split("|");',
  '  var cLbl=cp[1]||"";',
  '  if($("duty")&&$("duty").checked)cLbl=cLbl.replace(/\\.?$/,"")+\" (Duty).\";',
  '  var layout=fv("layoutStyle");',
  '  var showStamp=$("stampSpace")&&$("stampSpace").checked;',
  '  var ls=layout==="compact"?"1.35":"1.6";',
  '  var fs=layout==="compact"?"12pt":"13pt";',
  '  var caseHtml="";',
  '  if(fv("caseMode")==="appeal"){',
  '    var arr=[fv("caseType"),fv("caseNumber")].filter(Boolean);',
  '    caseHtml=arr.length?\'<div class="case-info">\'+arr.map(esc).join("<br>")+"</div>":"";',
  '  }else{',
  '    var arr2=[];',
  '    var fn=fv("firNumber"),fd=fv("firDate");',
  '    if(fn||fd)arr2.push("FIR No. "+esc(fn||"_____")+(fd?" dated "+esc(fd):""));',
  '    if(fv("sections"))arr2.push("U/s "+esc(fv("sections")));',
  '    if(fv("policeStation"))arr2.push("PS "+esc(fv("policeStation")));',
  '    caseHtml=arr2.length?\'<div class="fir-info">\'+arr2.join(",<br>")+"</div>":"";',
  '  }',
  '  var clausesHtml=state.clauses.filter(function(x){return clean(x);}).map(function(x,i){',
  '    return \'<div class="clause"><div class="clause-num">\'+(i+1)+\')</div><div class="clause-text">\'+esc(x)+"</div></div>";',
  '  }).join("");',
  '  $("paper").innerHTML=',
  '    \'<div class="paper-inner" style="font-size:\'+fs+\';line-height:\'+ls+\';">\'+',
  '    (showStamp?\'<div class="stamp-box">Court Fee<br>Ticket</div>\':"")+',
  '    \'<div class="court">\'+esc(fv("court"))+"</div>"+',
  '    \'<div class="case-grid"><div class="case-left">\'+esc(fv("leftParty")||"State/Complainant")+\'</div><div class="case-vs">v/s</div><div class="case-right">\'+esc(fv("rightParty")||"Accused/Respondent")+"</div>"+caseHtml+"</div>"+',
  '    \'<div class="subject">\'+esc($("subject").value||generateSubject())+"</div>"+',
  '    \'<div class="salutation">\'+esc(fv("salutation")||"Respected Sir,")+"</div>"+',
  '    \'<div class="intro">It is most respectfully submitted as follows:</div>\'+',
  '    clausesHtml+',
  '    \'<div class="prayer">\'+esc($("prayer").value||generatePrayer())+"</div>"+',
  '    \'<div class="sig-grid"><div class="sig-left"><b>Place:</b> \'+esc(fv("place")||"_____")+"<br><b>Date:</b> "+esc(fv("date")||"_____")+"</div>"+',
  '    \'<div class="sig-right"><b>Submitted By,</b><br><br><br><span class="sig-name">\'+esc(applicantText())+"<br>("+esc(accusedLabel())+")</span></div></div>"+',
  '    \'<div class="counsel-label">Through Counsel</div>\'+',
  '    \'<div class="counsel-details"><b>\'+esc(cp[0])+"</b><br>"+esc(cLbl)+"</div>"+',
  '    "</div>";',
  '}',

  // ── WORD WRAP ─────────────────────────────────────────────────────────────
  'function wordWrap(text,maxChars){',
  '  var words=String(text||"").split(/\\s+/);',
  '  var lines=[];var cur="";',
  '  for(var i=0;i<words.length;i++){',
  '    var w=words[i];if(!w)continue;',
  '    if(cur&&(cur+" "+w).length>maxChars){lines.push(cur);cur=w;}',
  '    else{cur=cur?cur+" "+w:w;}',
  '  }',
  '  if(cur)lines.push(cur);',
  '  return lines.length?lines:[""];',
  '}',

  'function estimateWidth(text,size,bold){return text.length*size*(bold?0.50:0.46);}',

  // ── RAW PDF ───────────────────────────────────────────────────────────────
  'function generateRealPdf(){',
  '  if(state.exporting)return;',
  '  var btn=$("realPdfBtn");',
  '  setExportState(btn,true,"Generating...",false);',
  '  requestAnimationFrame(function(){',
  '    try{_buildRawPdf();showToast("PDF exported successfully!","success");}',
  '    catch(err){showToast("Export failed: "+err.message,"error");console.error(err);}',
  '    finally{setExportState(btn,false,"Export PDF",false);}',
  '  });',
  '}',

  'function _buildRawPdf(){',
  '  var texts=[];',
  '  var isC=fv("layoutStyle")==="compact";',
  '  var sz=isC?12:13;var lh=isC?18:22;var y=72;',
  '  function push(t,x,b,a){texts.push({t:clean(t),x:x,y:y,size:sz,bold:!!b,align:a||"left"});}',
  '  function line(t,x,b,a){push(t,x||72,b,a);y+=lh;}',
  '  function center(t,b){line(t,306,b,"center");}',
  '  function right(t,b){line(t,540,b,"right");}',
  '  fv("court").split(/\\n/).forEach(function(t){center(t.toUpperCase(),true);});',
  '  y+=lh*1.5;',
  '  push(fv("leftParty")||"State/Complainant",72,true,"left");',
  '  push("v/s",306,true,"center");',
  '  push(fv("rightParty")||"Accused/Respondent",540,true,"right");',
  '  y+=lh;',
  '  if(fv("caseMode")==="appeal"){',
  '    if(fv("caseType"))center(fv("caseType"),true);',
  '    if(fv("caseNumber"))center(fv("caseNumber"),true);',
  '  }else{',
  '    var fn=fv("firNumber"),fd=fv("firDate");',
  '    if(fn||fd)center("FIR No. "+(fn||"_____")+(fd?" dated "+fd:""));',
  '    if(fv("sections"))center("U/s "+fv("sections"));',
  '    if(fv("policeStation"))center("PS "+fv("policeStation"));',
  '  }',
  '  y+=lh;',
  '  wordWrap($("subject").value||generateSubject(),80).forEach(function(l){line(l,72,true);});',
  '  y+=lh;',
  '  line(fv("salutation")||"Respected Sir,");',
  '  line("It is most respectfully submitted as follows:",108);',
  '  state.clauses.filter(function(c){return clean(c);}).forEach(function(c,i){',
  '    wordWrap(c,75).forEach(function(l,idx){',
  '      if(idx===0){push((i+1)+")",72,false,"left");line(l,100);}',
  '      else line(l,100);',
  '    });',
  '  });',
  '  y+=lh*0.5;',
  '  wordWrap($("prayer").value||generatePrayer(),75).forEach(function(l){line(l,100);});',
  '  y+=lh*2;',
  '  push("Place: "+(fv("place")||"_____"),72,false,"left");',
  '  right("Submitted By,",true);y+=lh;',
  '  push("Date: "+(fv("date")||"_____"),72,false,"left");',
  '  y+=lh*2.5;',
  '  right(applicantText(),true);y+=lh;',
  '  right("("+accusedLabel()+")");y+=lh*2;',
  '  var cp=fv("counsel").split("|");',
  '  var cLbl=cp[1]||"";',
  '  if($("duty")&&$("duty").checked)cLbl=cLbl.replace(/\\.?$/,"")+\" (Duty).\";',
  '  center("Through Counsel");y+=lh*1.5;',
  '  center(cp[0],true);center(cLbl,false);',
  '  compilePdfOutput(texts,null,"Exemption_Application.pdf");',
  '}',

  // ── SCANNED PDF ───────────────────────────────────────────────────────────
  'function generateScannedPdf(){',
  '  if(state.exporting)return;',
  '  var btn=$("scanPdfBtn");',
  '  setExportState(btn,true,"Scanning...",true);',
  '  setTimeout(function(){',
  '    try{_buildScannedPdf();showToast("Scanned PDF exported!","success");}',
  '    catch(err){showToast("Scan export failed: "+err.message,"error");console.error(err);}',
  '    finally{setExportState(btn,false,"Scanned PDF",true);}',
  '  },80);',
  '}',

  'function _buildScannedPdf(){',
  '  document.body.classList.add("exporting");',
  '  var paper=$("paper");',
  '  var oldTrans=paper.style.transform;',
  '  paper.style.transform="none";',
  '  var scale=window.devicePixelRatio>1?2:1.5;',
  '  var canvas=document.createElement("canvas");',
  '  canvas.width=Math.round(612*scale);canvas.height=Math.round(1008*scale);',
  '  var ctx=canvas.getContext("2d");',
  '  ctx.fillStyle="#ffffff";ctx.fillRect(0,0,canvas.width,canvas.height);',
  '  ctx.scale(scale,scale);ctx.fillStyle="#111111";ctx.textBaseline="top";',
  '  var isC=fv("layoutStyle")==="compact";',
  '  var sz=isC?12:13;var lh=isC?18:22;var y=72;',
  '  function setFont(b,s){ctx.font=(b?"bold ":"")+((s||sz))+"px \\"Times New Roman\\",Times,serif";}',
  '  function write(t,x,align){ctx.textAlign=align||"left";ctx.fillText(String(t||""),x,y);}',
  '  setFont(true,sz+1);',
  '  fv("court").split(/\\n/).forEach(function(t){write(t.toUpperCase(),306,"center");y+=lh;});',
  '  y+=lh;',
  '  setFont(true,sz);',
  '  write(fv("leftParty")||"State/Complainant",72);',
  '  write("v/s",306,"center");',
  '  write(fv("rightParty")||"Accused/Respondent",540,"right");',
  '  y+=lh;',
  '  setFont(false,sz);',
  '  if(fv("caseMode")==="appeal"){',
  '    setFont(true,sz);',
  '    if(fv("caseType")){write(fv("caseType"),306,"center");y+=lh;}',
  '    if(fv("caseNumber")){write(fv("caseNumber"),306,"center");y+=lh;}',
  '  }else{',
  '    var fn=fv("firNumber"),fd=fv("firDate");',
  '    if(fn||fd){write("FIR No. "+(fn||"_____")+(fd?" dated "+fd:""),306,"center");y+=lh;}',
  '    if(fv("sections")){write("U/s "+fv("sections"),306,"center");y+=lh;}',
  '    if(fv("policeStation")){write("PS "+fv("policeStation"),306,"center");y+=lh;}',
  '  }',
  '  y+=lh;',
  '  setFont(true,sz);',
  '  wordWrap($("subject").value||generateSubject(),80).forEach(function(l){',
  '    var tw=ctx.measureText(l).width;',
  '    write(l,72);',
  '    ctx.beginPath();ctx.strokeStyle="#000";ctx.lineWidth=0.8;',
  '    ctx.moveTo(72,y+sz+2);ctx.lineTo(72+tw,y+sz+2);ctx.stroke();',
  '    y+=lh;',
  '  });',
  '  y+=lh;',
  '  setFont(false,sz);',
  '  write(fv("salutation")||"Respected Sir,",72);y+=lh;',
  '  write("It is most respectfully submitted as follows:",108);y+=lh;',
  '  state.clauses.filter(function(c){return clean(c);}).forEach(function(c,i){',
  '    wordWrap(c,75).forEach(function(l,idx){',
  '      if(idx===0){write((i+1)+")",72);write(l,100);}else{write(l,100);}',
  '      y+=lh;',
  '    });',
  '  });',
  '  y+=lh*0.5;',
  '  wordWrap($("prayer").value||generatePrayer(),75).forEach(function(l){write(l,100);y+=lh;});',
  '  y+=lh*2;',
  '  write("Place: "+(fv("place")||"_____"),72);',
  '  setFont(true,sz);write("Submitted By,",540,"right");y+=lh;',
  '  setFont(false,sz);write("Date: "+(fv("date")||"_____"),72);y+=lh*2.5;',
  '  setFont(true,sz);write(applicantText(),540,"right");y+=lh;',
  '  setFont(false,sz);write("("+accusedLabel()+")",540,"right");y+=lh*2;',
  '  var cp2=fv("counsel").split("|");',
  '  var cLbl2=cp2[1]||"";',
  '  if($("duty")&&$("duty").checked)cLbl2=cLbl2.replace(/\\.?$/,"")+\" (Duty).\";',
  '  write("Through Counsel",306,"center");y+=lh*1.5;',
  '  setFont(true,sz);write(cp2[0],306,"center");y+=lh;',
  '  setFont(false,sz);write(cLbl2,306,"center");',
  '  var jpegData=canvas.toDataURL("image/jpeg",0.92);',
  '  paper.style.transform=oldTrans;',
  '  document.body.classList.remove("exporting");',
  '  compilePdfOutput([],jpegData,"Exemption_Application_Scanned.pdf");',
  '}',

  // ── PDF COMPILER ──────────────────────────────────────────────────────────
  'function compilePdfOutput(texts,jpegData,filename){',
  '  var objs=[];var content="";var imgId=null;',
  '  if(jpegData){',
  '    var raw=atob(jpegData.split(",")[1]);',
  '    var u8=new Uint8Array(raw.length);',
  '    for(var i=0;i<raw.length;i++)u8[i]=raw.charCodeAt(i);',
  '    var imgStream=String.fromCharCode.apply(null,u8);',
  '    objs.push("<< /Type /XObject /Subtype /Image /Width 1224 /Height 2016 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length "+imgStream.length+" >>\\nstream\\n"+imgStream+"\\nendstream");',
  '    imgId=objs.length;content="q 612 0 0 1008 0 0 cm /Im1 Do Q";',
  '  }else{',
  '    function escapePdf(s){return String(s||"").replace(/\\\\/g,"\\\\\\\\").replace(/\\(/g,"\\\\(").replace(/\\)/g,"\\\\)").replace(/[\\x00-\\x1f\\x7f-\\xff]/g,function(c){return "\\\\"+c.charCodeAt(0).toString(8).padStart(3,"0");});}',
  '    texts.forEach(function(o){',
  '      var tw=estimateWidth(o.t,o.size,o.bold);',
  '      var x=o.x;',
  '      if(o.align==="center")x-=tw/2;',
  '      if(o.align==="right")x-=tw;',
  '      x=Math.max(36,Math.round(x));',
  '      content+="BT /F"+(o.bold?"2":"1")+" "+o.size+" Tf "+x+" "+(1008-o.y)+" Td ("+escapePdf(o.t)+") Tj ET\\n";',
  '    });',
  '  }',
  '  var contentBytes=new Uint8Array(content.length);',
  '  for(var j=0;j<content.length;j++)contentBytes[j]=content.charCodeAt(j)&0xff;',
  '  objs.push("<< /Length "+contentBytes.length+" >>\\nstream\\n"+content+"\\nendstream");',
  '  var cId=objs.length,pId=cId+1,psId=cId+2,catId=cId+3,f1Id=cId+4,f2Id=cId+5;',
  '  var resDict=jpegData',
  '    ?"<< /Font << /F1 "+f1Id+" 0 R /F2 "+f2Id+" 0 R >> /XObject << /Im1 "+imgId+" 0 R >> >>"',
  '    :"<< /Font << /F1 "+f1Id+" 0 R /F2 "+f2Id+" 0 R >> >>";',
  '  objs.push("<< /Type /Page /Parent "+psId+" 0 R /MediaBox [0 0 612 1008] /Resources "+resDict+" /Contents "+cId+" 0 R >>");',
  '  objs.push("<< /Type /Pages /Kids ["+pId+" 0 R] /Count 1 >>");',
  '  objs.push("<< /Type /Catalog /Pages "+psId+" 0 R >>");',
  '  objs.push("<< /Type /Font /Subtype /Type1 /BaseFont /Times-Roman >>");',
  '  objs.push("<< /Type /Font /Subtype /Type1 /BaseFont /Times-Bold >>");',
  '  var pdf="%PDF-1.4\\n";var xref=[0];',
  '  objs.forEach(function(o,i){xref.push(pdf.length);pdf+=(i+1)+" 0 obj\\n"+o+"\\nendobj\\n";});',
  '  var sxref=pdf.length;',
  '  pdf+="xref\\n0 "+(objs.length+1)+"\\n0000000000 65535 f \\n";',
  '  xref.slice(1).forEach(function(x){pdf+=String(x).padStart(10,"0")+" 00000 n \\n";});',
  '  pdf+="trailer << /Size "+(objs.length+1)+" /Root "+catId+" 0 R >>\\nstartxref\\n"+sxref+"\\n%%EOF";',
  '  var pdfU8=new Uint8Array(pdf.length);',
  '  for(var k=0;k<pdf.length;k++)pdfU8[k]=pdf.charCodeAt(k)&0xff;',
  '  var blob=new Blob([pdfU8],{type:"application/pdf"});',
  '  var url=URL.createObjectURL(blob);',
  '  var a=document.createElement("a");',
  '  a.href=url;a.download=filename;',
  '  document.body.appendChild(a);a.click();',
  '  setTimeout(function(){URL.revokeObjectURL(url);a.remove();},2000);',
  '}',

  // ── EXPORT STATE ──────────────────────────────────────────────────────────
  'function setExportState(btn,loading,label,dark){',
  '  state.exporting=loading;',
  '  if(loading){',
  '    btn.disabled=true;',
  '    btn.dataset.orig=btn.innerHTML;',
  '    btn.innerHTML=\'<span class="btn-spinner\'+(dark?\' dark\':\'\')+\'"></span> \'+esc(label);',
  '    $("realPdfBtn").disabled=true;$("scanPdfBtn").disabled=true;',
  '  }else{',
  '    btn.disabled=false;',
  '    btn.innerHTML=btn.dataset.orig||label||btn.innerHTML;',
  '    $("realPdfBtn").disabled=false;$("scanPdfBtn").disabled=false;',
  '  }',
  '}',

  // ── LAYOUT / ZOOM ─────────────────────────────────────────────────────────
  'function fitPreview(){',
  '  var isD=window.innerWidth>=900;',
  '  var avail=window.innerWidth-(isD?460:0)-(isD?56:32);',
  '  state.zoom=Math.min(1,Math.max(0.15,avail/612));',
  '  document.documentElement.style.setProperty("--z",state.zoom.toFixed(4));',
  '}',

  'function toggleView(v){',
  '  document.body.className="view-"+v;',
  '  $("formTab").classList.toggle("active",v!=="preview");',
  '  $("previewTab").classList.toggle("active",v==="preview");',
  '  $("formTab").setAttribute("aria-selected",String(v!=="preview"));',
  '  $("previewTab").setAttribute("aria-selected",String(v==="preview"));',
  '  fitPreview();',
  '}',

  // ── EVENTS ────────────────────────────────────────────────────────────────
  'function bindEvents(){',
  '  document.body.addEventListener("input",function(e){',
  '    var el=e.target;',
  '    if(el.classList.contains("applicant")){state.people[+el.dataset.i].name=el.value;resetText();return;}',
  '    if(el.classList.contains("role")){state.people[+el.dataset.i].role=el.value;updatePreview();return;}',
  '    if(el.classList.contains("clauseText")){state.clauses[+el.dataset.i]=el.value;updatePreview();return;}',
  '    if(el.id==="reason"||el.id==="caseStage"){resetText();return;}',
  '    updatePreview();',
  '  });',
  '  document.body.addEventListener("change",function(e){',
  '    if(e.target.id==="proforma"){applyProforma();return;}',
  '    $("firFields").classList.toggle("hidden",fv("caseMode")!=="fir");',
  '    $("appealFields").classList.toggle("hidden",fv("caseMode")!=="appeal");',
  '    updatePreview();',
  '  });',
  '  document.body.addEventListener("click",function(e){',
  '    var id=e.target.id,cl=e.target.classList;',
  '    if(id==="formTab"){toggleView("form");return;}',
  '    if(id==="previewTab"){toggleView("preview");return;}',
  '    if(id==="addApplicant"){state.people.push({name:"",role:"Accused/applicant"});renderApplicants();resetText();return;}',
  '    if(cl.contains("delApplicant")){',
  '      state.people.splice(+e.target.dataset.i,1);',
  '      if(!state.people.length)state.people=[{name:"",role:"Accused/applicant"}];',
  '      renderApplicants();resetText();return;',
  '    }',
  '    if(id==="addClause"){state.clauses.push("");renderClauses();updatePreview();return;}',
  '    if(id==="resetClauses"){state.clauses=generateDefaultClauses();renderClauses();updatePreview();return;}',
  '    if(cl.contains("delClause")){state.clauses.splice(+e.target.dataset.i,1);renderClauses();updatePreview();return;}',
  '    if(id==="realPdfBtn"){generateRealPdf();return;}',
  '    if(id==="scanPdfBtn"){generateScannedPdf();return;}',
  '  });',
  '  window.addEventListener("resize",debounce(fitPreview,150));',
  '}',

  // ── INIT ──────────────────────────────────────────────────────────────────
  'function renderApp(){',
  '  var styleEl=document.createElement("style");',
  '  styleEl.id="pdfwriter-styles";',
  '  styleEl.textContent=getCSS();',
  '  document.head.appendChild(styleEl);',
  '  document.body.className="view-form";',
  '  $("app").innerHTML=getHTML();',
  '  $("proforma").innerHTML=CONFIG.proformas.map(function(p){return \'<option value="\'+escAttr(p.id)+\'">\'+esc(p.name)+"</option>";}).join("");',
  '  $("court").innerHTML=CONFIG.courts.map(function(c){return \'<option value="\'+escAttr(c)+\'">\'+esc(c.replace("IN THE COURT OF ",""))+"</option>";}).join("");',
  '  $("counsel").innerHTML=CONFIG.counsels.map(function(c){var pts=c.split("|");return \'<option value="\'+escAttr(c)+\'">\'+esc(pts[0])+" — "+esc((pts[1]||"").replace(", Fazilka.",""))+"</option>";}).join("");',
  '  resetText();renderApplicants();bindEvents();fitPreview();',
  '  var loader=document.getElementById("loader");',
  '  if(loader){loader.style.opacity="0";setTimeout(function(){loader.remove();},350);}',
  '}',

  'document.addEventListener("DOMContentLoaded",renderApp);',
  '})();'
].join('\n');
