import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { z } from 'zod';

const $ = (id) => document.getElementById(id);
const esc = (s) => String(s || '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const clean = (s) => String(s || '').replace(/[.\s]+$/g, '').trim();

const store = {
  people: [{ name: '', role: 'Accused/applicant' }],
  clauses: [],
  zoom: 0.48,
  view: 'draft'
};

const TemplateSchema = z.object({
  format: z.literal('PdfWriterTemplate'),
  version: z.number(),
  fields: z.record(z.any()),
  people: z.array(z.object({ name: z.string().optional(), role: z.string().optional() })).optional(),
  clauses: z.array(z.string()).optional()
});

function namesArray(){ return store.people.map((p) => clean(p.name)).filter(Boolean); }
function isPlural(){ return namesArray().length > 1; }
function namesText(){ const a = namesArray(); return a.length < 2 ? (a[0] || '') : a.length === 2 ? a[0] + ' and ' + a[1] : a.slice(0, -1).join(', ') + ' and ' + a.at(-1); }
function applicantLabel(){ return namesText() || clean(value('caseRight')) || 'Accused/applicant'; }
function value(id){ return ($(id)?.value || '').trim(); }
function defaultSubject(){ const n = namesText(); return 'Application for exemption of personal appearance' + (n ? ' of ' + n : '') + '.'; }
function defaultPrayer(){ return 'It is therefore respectfully prayed that, in view of the facts and circumstances stated above, the personal appearance of the ' + (isPlural() ? 'above-named accused/applicants' : 'accused/applicant') + ' may kindly be exempted for today only.'; }
function attendance(){ const n = namesText(); if (!n) return "That the accused/applicant is unable to appear before this Hon'ble Court due to illness."; return 'That ' + (isPlural() ? 'the accused/applicants, namely ' + n + ', are' : 'the accused/applicant ' + n + ' is') + " unable to appear before this Hon'ble Court due to illness."; }
function defaultClauses(){ return ["That the above noted case is pending before this Hon'ble Court and is fixed for today.", attendance(), 'That the absence is neither willful nor intentional, but due to the reason stated above.']; }

function mountForm(){
  $('draftForm').innerHTML = `
    <section class="card"><div class="card-title"><div class="title-left"><span>01</span><h2>Court and case title</h2></div></div>
      <label>Court name</label><select id="court" class="field">
        <option value="IN THE COURT OF SH. DHARMINDER PAUL SINGLA, SESSIONS JUDGE, FAZILKA">Sh. Dharminder Paul Singla, Sessions Judge, Fazilka</option>
        <option value="IN THE COURT OF SH. KRISHAN KUMAR SINGLA, ASJ, FAZILKA">Sh. Krishan Kumar Singla, ASJ, Fazilka</option>
        <option value="IN THE COURT OF MRS. PAMELPREET GREWAL KAHAL, ASJ, FAZILKA">Mrs. Pamelpreet Grewal Kahal, ASJ, Fazilka</option>
        <option value="IN THE COURT OF MRS. PAMELPREET GREWAL KAHAL, JUDGE, SPECIAL COURT, FAZILKA">Mrs. Pamelpreet Grewal Kahal, Special Court, Fazilka</option>
        <option selected value="IN THE COURT OF SH. AJIT PAL SINGH, ASJ, FAZILKA">Sh. Ajit Pal Singh, ASJ, Fazilka</option>
        <option value="IN THE COURT OF SH. ATUL KAMBOJ, ASJ, FAZILKA">Sh. Atul Kamboj, ASJ, Fazilka</option>
        <option value="IN THE COURT OF SH. HARPREET SINGH, JMIC, FAZILKA">Sh. Harpreet Singh, JMIC, Fazilka</option>
        <option value="IN THE COURT OF MS. KARAMWINDER KAUR, JMIC, FAZILKA">Ms. Karamwinder Kaur, JMIC, Fazilka</option>
      </select>
      <div class="grid grid-2"><div><label>Case title left</label><input id="caseLeft" class="field" placeholder="State / Complainant"></div><div><label>Case title right</label><input id="caseRight" class="field" placeholder="Accused / Respondent"></div></div>
      <p class="hint">The case title is aligned automatically. It may differ from the absent accused/applicant name.</p>
    </section>
    <section class="card"><div class="card-title"><div class="title-left"><span>02</span><h2>FIR details</h2></div><small>Optional</small></div>
      <div class="grid grid-2"><div><label>FIR number</label><input id="fir" class="field" placeholder="FIR No."></div><div><label>FIR date</label><input id="firDate" class="field" placeholder="DD.MM.YYYY"></div><div><label>Sections</label><input id="sections" class="field" placeholder="Sections / Act"></div><div><label>Police station</label><input id="policeStation" class="field" placeholder="Police Station"></div></div>
    </section>
    <section class="card"><div class="card-title"><div class="title-left"><span>03</span><h2>Absent accused / applicants</h2></div><button id="addPerson" class="btn soft" type="button">Add person</button></div><div id="peopleBox" class="stack"></div></section>
    <section class="card"><div class="card-title"><div class="title-left"><span>04</span><h2>Application text</h2></div><button id="resetText" class="btn soft" type="button">Reset text</button></div><label>Subject</label><textarea id="subject" class="field area"></textarea><label>Prayer</label><textarea id="prayer" class="field area"></textarea></section>
    <section class="card"><div class="card-title"><div class="title-left"><span>05</span><h2>Factual statements</h2></div><button id="addClause" class="btn soft" type="button">Add clause</button></div><div id="clauseBox" class="stack"></div></section>
    <section class="card"><div class="card-title"><div class="title-left"><span>06</span><h2>Filing and counsel</h2></div></div><div class="grid grid-2"><div><label>Place</label><input id="place" class="field" placeholder="Place"></div><div><label>Date</label><input id="date" class="field" placeholder="DD.MM.YYYY"></div></div><label>Through counsel</label><select id="counsel" class="field"><option value="Baltej Singh Brar, Advocate|Chief, LADC, Fazilka.">Baltej Singh Brar — Chief</option><option value="Hardeep Singh Dhaliwal, Advocate|Deputy Chief, LADC, Fazilka.">Hardeep Singh Dhaliwal — Deputy Chief</option><option value="Sunil Rangbulla, Advocate|Deputy Chief, LADC, Fazilka.">Sunil Rangbulla — Deputy Chief</option><option value="Rajvinder Kaur, Advocate|Assistant, LADC, Fazilka.">Rajvinder Kaur — Assistant</option><option value="Amisha, Advocate|Assistant, LADC, Fazilka.">Amisha — Assistant</option><option selected value="Naazpreet Kaur, Advocate|Assistant, LADC, Fazilka.">Naazpreet Kaur — Assistant</option></select><label class="check"><input id="duty" type="checkbox"> Add (Duty) after counsel designation</label></section>`;
}

function renderPeople(){ $('peopleBox').innerHTML = store.people.map((p, i) => `<div class="person-row"><div class="grid grid-2"><div><label>Name ${i + 1}</label><input class="field person-name" data-index="${i}" placeholder="Name" value="${esc(p.name)}"></div><div><label>Role</label><input class="field person-role" data-index="${i}" value="${esc(p.role || 'Accused/applicant')}"></div></div><div class="row-actions"><button class="btn soft person-up" data-index="${i}" type="button">Up</button><button class="btn soft person-down" data-index="${i}" type="button">Down</button><button class="btn danger person-delete" data-index="${i}" type="button">Delete</button></div></div>`).join(''); }
function renderClauses(){ $('clauseBox').innerHTML = store.clauses.map((c, i) => `<div class="clause-row"><textarea class="field area clause-text" data-index="${i}">${esc(c)}</textarea><div class="row-actions"><button class="btn soft clause-up" data-index="${i}" type="button">Up</button><button class="btn soft clause-down" data-index="${i}" type="button">Down</button><button class="btn danger clause-delete" data-index="${i}" type="button">Delete</button></div></div>`).join(''); }
function resetText(){ $('subject').value = defaultSubject(); $('prayer').value = defaultPrayer(); store.clauses = defaultClauses(); renderClauses(); renderPreview(); }
function counselParts(){ const [name = '', raw = ''] = value('counsel').split('|'); let line = raw; if ($('duty')?.checked) line = line.replace(/\.?$/,'') + ' (Duty).'; return { name, line }; }
function firBlock(){ const rows = []; if (value('fir') || value('firDate')) rows.push('FIR No. ' + esc(value('fir') || '_____') + (value('firDate') ? ' dated ' + esc(value('firDate')) : '')); if (value('sections')) rows.push('U/s ' + esc(value('sections'))); if (value('policeStation')) rows.push('PS ' + esc(value('policeStation'))); return rows.join(',<br>'); }
function renderPreview(){ const c = counselParts(); const plural = isPlural() ? 'Accused/applicants' : 'Accused/applicant'; let n = 1; const clauses = store.clauses.filter((x) => clean(x)).map((x) => `<div class="clause"><div>${n++})</div><div>${esc(x)}</div></div>`).join(''); $('paper').innerHTML = `<div class="paper-inner"><div class="court">${esc(value('court'))}</div><div class="stamp"></div><div class="case-grid"><div>${esc(value('caseLeft') || 'State')}</div><div class="case-vs">v/s</div><div class="case-right">${esc(value('caseRight') || 'Accused')}</div><div class="fir-block">${firBlock()}</div></div><div class="subject">${esc(value('subject') || defaultSubject())}</div><div style="margin-bottom:14px">Respected Sir,</div><div style="margin-bottom:15px;text-indent:38px">It is submitted as follows:</div>${clauses}<div class="prayer">${esc(value('prayer') || defaultPrayer())}</div><div class="sig"><div>Place: ${esc(value('place') || '_____')}<br>Date: ${esc(value('date') || '_____')}</div><div class="sig-right">Submitted By<br><br><br><span class="sig-name"><b>${esc(applicantLabel())}</b><br>(${plural})</span></div></div><div class="counsel-block">Through Counsel<br><br><br><b>${esc(c.name)}</b><br>${esc(c.line)}</div></div>`; $('statusText').textContent = 'Preview updated'; }

function setView(view){ store.view = view; document.body.classList.toggle('view-draft', view === 'draft'); document.body.classList.toggle('view-preview', view === 'preview'); document.querySelectorAll('[data-view]').forEach((b) => b.classList.toggle('is-active', b.dataset.view === view)); fitPreview(); }
function fitPreview(){ store.zoom = Math.min(1, Math.max(.34, (innerWidth - 28) / 816)); document.documentElement.style.setProperty('--zoom', String(store.zoom)); }
function zoom(d){ store.zoom = Math.min(1.4, Math.max(.3, store.zoom + d)); document.documentElement.style.setProperty('--zoom', String(store.zoom)); }

function collect(){ const ids = ['court','caseLeft','caseRight','fir','firDate','sections','policeStation','subject','prayer','place','date','counsel','duty']; const fields = {}; ids.forEach((id) => { const el = $(id); fields[id] = el.type === 'checkbox' ? el.checked : el.value; }); return { format: 'PdfWriterTemplate', version: 21, fields, people: store.people, clauses: store.clauses }; }
function applyTemplate(data){ const parsed = TemplateSchema.parse(data); store.people = parsed.people?.length ? parsed.people.map((p) => ({ name: p.name || '', role: p.role || 'Accused/applicant' })) : [{ name: '', role: 'Accused/applicant' }]; store.clauses = parsed.clauses || defaultClauses(); Object.entries(parsed.fields || {}).forEach(([id, v]) => { const el = $(id); if (!el) return; if (el.type === 'checkbox') el.checked = Boolean(v); else el.value = String(v ?? ''); }); renderPeople(); renderClauses(); renderPreview(); }
function downloadTemplate(){ const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([JSON.stringify(collect(), null, 2)], { type: 'application/json' })); a.download = 'pdfwriter-template.pwt.json'; a.click(); URL.revokeObjectURL(a.href); }

async function scannedPdf(){ document.body.classList.add('exporting'); const paper = $('paper'); const old = paper.style.transform; paper.style.transform = 'none'; await new Promise((r) => setTimeout(r, 80)); try { const canvas = await html2canvas(paper, { scale: 3, backgroundColor: '#fff' }); const pdf = new jsPDF({ unit: 'in', format: 'legal' }); pdf.addImage(canvas.toDataURL('image/jpeg', .96), 'JPEG', 0, 0, 8.5, 14); pdf.save('Application_scanned.pdf'); } finally { paper.style.transform = old; document.body.classList.remove('exporting'); } }
function rawPdf(){ const pdf = new jsPDF({ unit: 'pt', format: 'legal' }); const m = 86, w = 440; let y = 60; const line = (t, x = m, opt = {}) => { pdf.text(String(t || ''), x, y, opt); y += 18; }; const wrap = (t, x = m, width = w, indent = 0) => pdf.splitTextToSize(String(t || ''), width - indent).forEach((l, i) => line(l, x + (i ? 0 : indent), { maxWidth: width })); pdf.setFont('times', 'bold'); pdf.setFontSize(13); pdf.splitTextToSize(value('court').toUpperCase(), w).forEach((l) => line(l, 306, { align: 'center' })); y += 88; line(value('caseLeft') || 'State', m); pdf.text('v/s', 306, y - 18, { align: 'center' }); pdf.text(value('caseRight') || 'Accused', m + w, y - 18, { align: 'right' }); pdf.setFont('times', 'normal'); y += 18; firBlock().replace(/<br>/g, '\n').split('\n').filter(Boolean).forEach((l) => line(l.replace(/&amp;/g, '&'), m + 205)); y += 18; pdf.setFont('times', 'bold'); wrap(value('subject') || defaultSubject()); y += 12; pdf.setFont('times', 'normal'); line('Respected Sir,'); line('It is submitted as follows:', m + 30); store.clauses.filter((c) => clean(c)).forEach((c, i) => { line((i + 1) + ')', m); y -= 18; wrap(c, m + 25, w - 25); y += 6; }); wrap(value('prayer') || defaultPrayer(), m, w, 30); y += 30; line('Place: ' + (value('place') || '_____')); y -= 18; pdf.text('Submitted By', m + w, y, { align: 'right' }); y += 18; line('Date: ' + (value('date') || '_____')); y += 34; pdf.setFont('times', 'bold'); pdf.text(applicantLabel(), m + w, y, { align: 'right' }); y += 16; pdf.setFont('times', 'normal'); pdf.text('(' + (isPlural() ? 'Accused/applicants' : 'Accused/applicant') + ')', m + w, y, { align: 'right' }); y += 58; const c = counselParts(); pdf.text('Through Counsel', 306, y, { align: 'center' }); y += 42; pdf.setFont('times', 'bold'); pdf.text(c.name, 306, y, { align: 'center' }); y += 16; pdf.setFont('times', 'normal'); pdf.text(c.line, 306, y, { align: 'center' }); pdf.save('Application_raw.pdf'); }

function bind(){ document.querySelectorAll('[data-view]').forEach((b) => b.onclick = () => setView(b.dataset.view)); $('[data-action="open-tools"]')?.addEventListener('click', () => $('templateTools').hidden = !$('templateTools').hidden); $('templateToggle').onclick = () => $('templateTools').hidden = !$('templateTools').hidden; $('addPerson').onclick = () => { store.people.push({ name: '', role: 'Accused/applicant' }); renderPeople(); resetText(); }; $('addClause').onclick = () => { store.clauses.push(''); renderClauses(); renderPreview(); }; $('resetText').onclick = resetText; $('previewButton').onclick = () => setView('preview'); $('rebuildPreview').onclick = renderPreview; $('fitPreview').onclick = fitPreview; $('zoomOut').onclick = () => zoom(-.06); $('zoomIn').onclick = () => zoom(.06); $('downloadScannedPdf').onclick = scannedPdf; $('downloadScannedPdf2').onclick = scannedPdf; $('downloadRawPdf').onclick = rawPdf; $('downloadRawPdf2').onclick = rawPdf; $('exportTemplate').onclick = downloadTemplate; $('importTemplate').onclick = () => $('templateFile').click(); $('templateFile').onchange = (e) => { const r = new FileReader(); r.onload = () => applyTemplate(JSON.parse(r.result)); r.readAsText(e.target.files[0]); }; $('saveDraft').onclick = () => localStorage.setItem('pdfwriter.draft', JSON.stringify(collect())); $('loadDraft').onclick = () => applyTemplate(JSON.parse(localStorage.getItem('pdfwriter.draft') || '{}')); $('draftForm').addEventListener('input', (e) => { if (e.target.classList.contains('person-name')) { store.people[+e.target.dataset.index].name = e.target.value; resetText(); return; } if (e.target.classList.contains('person-role')) { store.people[+e.target.dataset.index].role = e.target.value; renderPreview(); return; } if (e.target.classList.contains('clause-text')) { store.clauses[+e.target.dataset.index] = e.target.value; renderPreview(); return; } renderPreview(); }); $('draftForm').addEventListener('click', (e) => { const i = +e.target.dataset.index; if (e.target.classList.contains('person-delete')) { store.people.splice(i, 1); if (!store.people.length) store.people.push({ name: '', role: 'Accused/applicant' }); renderPeople(); resetText(); } if (e.target.classList.contains('clause-delete')) { store.clauses.splice(i, 1); renderClauses(); renderPreview(); } }); addEventListener('resize', fitPreview); }

document.addEventListener('DOMContentLoaded', () => { mountForm(); renderPeople(); resetText(); bind(); fitPreview(); });
